# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('datos_generales', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('1', 'vzor_suite'), ('2', 'vzor_cloud')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendedores.Empresa')),
                ('numero_de_monitores', models.IntegerField()),
                ('numero_de_pasos', models.IntegerField()),
                ('token', models.DateTimeField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
                ('producto_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendedores.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedores.Empresa'),
        ),
        migrations.AddField(
            model_name='productos',
            name='productos',
            field=models.ManyToManyField(related_name='productos_todos', to='vendedores.Producto'),
        ),
    ]
